Refactor message composer
RocketChat/Rocket.Chat.Android pull request #109
Opened 2016-12-22 16:11 UTC by YusukeIwaki

@RocketChat/android

![slice](https://cloud.githubusercontent.com/assets/11763113/21431924/af6c0d6a-c8ac-11e6-9016-c426564b5d22.png)

2016-12-22 21:01 UTC, laggedHero requested changes

2016-12-22 21:01 UTC, laggedHero commented on rocket-chat-android-widgets/src/main/java/chat/rocket/android/widget/message/MessageFormLayout.java
> +  public static final int EXTRA_ACTION_PICK_PHOTO = 1;
The message type cannot be static. It needs to be dynamic.

We need to define a plugin-like arch to support it.

2016-12-23 03:05 UTC, YusukeIwaki commented on rocket-chat-android-widgets/src/main/java/chat/rocket/android/widget/message/MessageFormLayout.java
> +  public static final int EXTRA_ACTION_PICK_PHOTO = 1;
Thank you for good advice.

I failed to consider that each server has different configurations about uploading feature.
I will fix...

2016-12-26 14:39 UTC, laggedHero approved these changes

2016-12-26 14:58 UTC, merged