[NEW] No chat message shown on empty chat list
RocketChat/Rocket.Chat.Android pull request #1167
Opened 2018-04-23 18:56 UTC by divyanshub024

@RocketChat/android

Closes #896 

![no-chat-msg](https://user-images.githubusercontent.com/16731434/39147000-0ab9041a-4756-11e8-8bcf-4bd96098c2e9.png)

2018-04-23 18:58 UTC, rafaelks commented
Looking great @divyanshub024! Can you fix the conflicts please?

2018-04-23 18:59 UTC, divyanshub024 commented
@rafaelks done!

2018-04-23 19:19 UTC, philipbrito requested changes
Take a look on the `colors.xml` and check if there is some color that looks like the ones you use here (if not, add your color there).

2018-04-23 19:19 UTC, philipbrito commented on app/src/main/res/layout/fragment_chat_room.xml
> +        android:textColor="#8B8B8B"
What about using the `colors.xml` here instead of this hard coded way?

2018-04-23 19:19 UTC, philipbrito commented on app/src/main/res/layout/fragment_chat_room.xml
> +        android:textColor="#c1c1c1"
What about using the `colors.xml` here instead of this hard coded way?

2018-04-23 19:19 UTC, philipbrito commented on app/src/main/res/layout/fragment_chat_room.xml
> +        android:tint="#AFADAF"
What about using the `colors.xml` here instead of this hard coded way?

2018-04-23 19:39 UTC, divyanshub024 commented
@filipedelimabrito requested changes are made

2018-04-23 19:41 UTC, filipedelimabrito commented
Thanks for this PR @divyanshub024 
♥️

2018-04-23 20:44 UTC, rafaelks commented
@divyanshub024 Looking great!!! I found one bug: if you load a chat until the beginning, it'll show the empty message also. Can you fix that please?

2018-04-26 00:16 UTC, rafaelks commented
@divyanshub024 Can you take a look on the bug please? 😀

2018-04-26 00:34 UTC, divyanshub024 commented
Sure!!

2018-04-26 17:04 UTC, divyanshub024 commented
@rafaelks Bug is solved now.

2018-04-27 13:01 UTC, rafaelks approved these changes
Looking great! 👏

2018-04-27 13:41 UTC, philipbrito approved these changes
Thanks for this PR @divyanshub024 !

2018-04-27 13:42 UTC, merged