[NEW] Wear Module
RocketChat/Rocket.Chat.Android pull request #1280
Opened 2018-05-16 20:10 UTC by aniketsingh03

@RocketChat/android

Wooho! The wear (android watch) app for Rocket Chat will be available soon. This is the first pull request in its making.

2018-05-21 21:21 UTC, filipedelimabrito commented
Why not using our app icon on the wear app?

2018-05-21 21:27 UTC, philipbrito requested changes

2018-05-21 21:27 UTC, filipedelimabrito commented on wear/src/main/res/values/strings.xml
> +    <string name="app_name">Wear</string>
Wear? It should be `Rocket.Chat` (like the Android app name).

2018-05-21 21:27 UTC, filipedelimabrito commented on wear/build.gradle
> +        versionName "1.0"
Change to `1.0.0` (semantic versioning).

2018-05-21 21:27 UTC, filipedelimabrito commented on wear/build.gradle
> +    implementation 'com.android.support:support-v4:26.1.0'
You can declare it as the same way we declare for the Android app. Change it please!

2018-05-21 21:27 UTC, filipedelimabrito commented on wear/build.gradle
> +
Remove this blank space.

2018-05-22 10:08 UTC, aniketsingh03 commented
@filipedelimabrito I'll just resolve all these issues and push in some moments.

2018-05-23 21:36 UTC, aniketsingh03 commented
@filipedelimabrito Are we planning to keep this from merging until we have some features in the app?

2018-05-24 21:15 UTC, philipbrito requested changes

2018-05-24 21:15 UTC, filipedelimabrito commented on wear/build.gradle
> +
Missing `buildToolsVersion versions.buildTools` here! 
In that way we are unable to launch the project.

2018-05-25 17:34 UTC, philipbrito approved these changes
Thanks @aniketsingh03!

2018-05-25 17:35 UTC, merged