[WIP] Showing Image Text Field
RocketChat/Rocket.Chat.Android pull request #1407
Opened 2018-06-25 07:51 UTC by ubarsaiyan

@RocketChat/android

Closes #ISSUE_NUMBER

2018-06-25 07:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1407) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1407) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=1407) it.</sub>

2018-06-25 07:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1407) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1407) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=1407) it.</sub>

2018-06-30 10:10 UTC, philipbrito requested changes
You need only to "fix" two things and there we go!

2018-06-30 10:10 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
> +        return with(attachment) {
`with()` here is useless. Could you remove that, please?

2018-06-30 10:10 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
> +        return with(attachment) {
`with()` here is useless. Could you remove that, please?

2018-07-03 11:20 UTC, filipedelimabrito commented
@ubarsaiyan Could you fix the CI? This is being unable to generate the apk.

2018-07-03 12:53 UTC, philipbrito approved these changes
Thanks for your first PR here @ubarsaiyan 
Welcome :)

2018-07-03 12:53 UTC, merged

2018-07-03 13:33 UTC, ubarsaiyan commented
Thank you 😊