Notify new message in the chat room
RocketChat/Rocket.Chat.Android pull request #1437
Opened 2018-07-05 12:14 UTC by shubhsherl

@RocketChat/android

Closes #1394 
Add count on fab_button to notify the user about the arrival of new messages.

Screenshot in message-
https://open.rocket.chat/channel/androidnativeapp?msg=Bsiev2z4wGMYCfa38

2018-07-05 12:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1437) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1437) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=1437) it.</sub>

2018-07-05 12:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1437) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1437) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=1437) it.</sub>

2018-07-05 12:44 UTC, divyanshub024 commented
I would suggest to upload the screenshot here rather than giving link.

2018-07-05 13:20 UTC, philipbrito reviewed
Just some suggestions...

2018-07-05 13:20 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +                text_count.visibility = View.INVISIBLE
Suggestion: You can use `text_count.isVisible = false` here

2018-07-05 13:20 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +                    if (newMessageCount !=0) text_count.visibility = View.VISIBLE
Suggestion: You can use `text_count.isVisible` here

2018-07-05 13:20 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +                text_count.visibility = View.VISIBLE
Suggestion: You can use `text_count.isVisible = true` here

2018-07-05 13:20 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +            if (isMessageReceived && button_fab.visibility == View.VISIBLE) {
Suggestion: You can use `button_fab.isVisible` here

2018-07-05 13:20 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +            else if (button_fab.visibility == View.GONE)
Suggestion: You can use `!button_fab.isVisible` here

2018-07-05 13:20 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +            text_count.visibility = View.INVISIBLE
Suggestion: You can use `text_count.isVisible = false` here

2018-07-05 13:26 UTC, philipbrito approved these changes

2018-07-05 13:26 UTC, philipbrito commented on app/src/main/res/drawable/round_textview.xml
> +android:height="20dp"
Wrong formatting. 
Try configuring your IDE with the [Kotlin Code Style](https://kotlinlang.org/docs/reference/coding-conventions.html#applying-the-style-guide) if it is not already configured.
Tip: You can use the combination `Ctrl + Option + L` to fix the formatting quickly!

2018-07-05 14:05 UTC, divyanshub024 requested changes

2018-07-05 14:05 UTC, divyanshub024 commented on app/src/main/res/layout/message_list.xml
> +
Remove extra line.

2018-07-05 14:05 UTC, divyanshub024 commented on app/src/main/res/layout/message_list.xml
> +
Remove extra line.

2018-07-05 14:05 UTC, divyanshub024 commented on app/src/main/res/layout/message_list.xml
> +
Remove extra line.

2018-07-05 14:05 UTC, divyanshub024 commented on app/src/main/res/layout/message_list.xml
> +
Remove extra line

2018-07-05 14:05 UTC, divyanshub024 commented on app/src/main/res/layout/message_list.xml
> +
Remove extra line.

2018-07-05 14:05 UTC, divyanshub024 commented on app/src/main/res/drawable/round_textview.xml
> +<solid android:color="#30a7fe" />
Use @color/colorAccent

2018-07-05 14:05 UTC, divyanshub024 commented on app/src/main/res/layout/message_list.xml
> +            android:layout_alignParentRight="true"
Use layout_alignParentEnd istead of layout_alignParentRight

2018-07-05 14:05 UTC, divyanshub024 commented on app/src/main/res/layout/message_list.xml
> +    <RelativeLayout
Can you remove relative layout and use app:layout_anchor="@id/button_fab" in textview instead so that we can have flat structure.(This is optional)

2018-07-05 16:39 UTC, philipbrito requested changes
I mistakenly approved the PR. 
It needs some changes as explained in the review comments.

2018-07-05 19:58 UTC, shubhsherl commented
Changes made as  requested

2018-07-05 20:00 UTC, shubhsherl commented on app/src/main/res/drawable/round_textview.xml
> +android:height="20dp"
@filipedelimabrito can you tell me values for Tab Size, Indent, and Continuation Indent which you prefer, so that I can set that in my IDE.

2018-07-06 04:45 UTC, divyanshub024 approved these changes

2018-07-11 13:09 UTC, filipedelimabrito commented on app/src/main/res/drawable/round_textview.xml
> +android:height="20dp"
Sorry for the delay. You only need to go to the link above to get the coding style and set that into your IDE.

2018-07-11 13:14 UTC, philipbrito approved these changes
Thank you very much for this PR @shubhsherl !

2018-07-11 13:14 UTC, merged