Fix Message retain issue
RocketChat/Rocket.Chat.Android pull request #1466
Opened 2018-07-10 13:01 UTC by shubhsherl

@RocketChat/android

Closes #1464 

Fix the message retain issue when there is text in message composer and user cancel the reply option.

2018-07-10 19:08 UTC, philipbrito requested changes
Could you only change a small piece of the code to just follow the coding style?

Thanks.

2018-07-10 19:08 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
>              KeyboardHelper.showSoftKeyboard(text_message)
Could you change it to:
```
if (text_message.textContent.isEmpty()) {
    KeyboardHelper.showSoftKeyboard(text_message)	             
}
``` 
?

2018-07-11 05:46 UTC, shubhsherl commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
>              KeyboardHelper.showSoftKeyboard(text_message)
Okay..

2018-07-11 11:12 UTC, philipbrito approved these changes
Thanks for submitting this PR @shubhsherl!

2018-07-11 11:12 UTC, merged