[NEW] Add room_privacy_changed system message handling
RocketChat/Rocket.Chat.Android pull request #1716
Opened 2018-10-02 02:22 UTC by leonardoaramaki

@RocketChat/android

Closes #1403

2018-10-02 11:45 UTC, rafaelks requested changes

2018-10-02 11:45 UTC, rafaelks commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="message_room_changed_privacy">Room type changed to: %1$s by %2$s</string>
👀

2018-10-04 13:39 UTC, philipbrito requested changes
Missing the `<!-- TODO Add translation -->` for strings that need to be translated.

2018-10-05 17:42 UTC, rafaelks approved these changes

2018-10-05 17:42 UTC, merged