[IMPROVEMENT] Add dialog confirmation for logout
RocketChat/Rocket.Chat.Android pull request #1717
Opened 2018-10-02 06:23 UTC by shubhsherl

@RocketChat/android

Closes #1715 
Add Logout Confirmation.

![roc](https://user-images.githubusercontent.com/34231951/46332338-b6f8e300-c639-11e8-9e33-ca463ac63ca3.png)

2018-10-02 11:46 UTC, rafaelks requested changes
Thanks for the PR! Just need to be localized.

2018-10-02 11:46 UTC, rafaelks commented on app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
> +        builder.setMessage("Are you sure ?")
Please use localised strings here

2018-10-04 06:18 UTC, shubhsherl commented
@rafaelks  PR updated.

2018-10-19 12:08 UTC, rafaelks commented
@shubhsherl Could you please change the text from `Are You Sure?` to `Are you sure you want to logout?`

2018-10-19 13:55 UTC, divyanshub024 reviewed
@shubhsherl It's prefered to add a title in a dialog. So title may be `Log out` and message may be `Are you sure you want to logout?`

2018-10-20 05:40 UTC, closed without merging