[NEW] Add support for (un)muted states
RocketChat/Rocket.Chat.Android pull request #1840
Opened 2018-11-06 00:09 UTC by leonardoaramaki

@RocketChat/android

Depends on https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/214

Closes #1825

2018-11-06 08:58 UTC, rafaelks requested changes
@leonardoaramaki It worked for me the first time, but after I unmute the user and muted the user again the status never changed to "muted"... it's looking nice when it show the correct state! 👍

2018-11-06 11:19 UTC, leonardoaramaki commented
@rafaelks Did you leave and reenter the channel? Remember that we still don't have updates for channels on socket.

2018-11-13 11:50 UTC, luciofm approved these changes

2018-11-13 11:50 UTC, luciofm commented on app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
> +import java.lang.IllegalArgumentException
👍

2018-11-13 12:24 UTC, merged