Farsi language added
RocketChat/Rocket.Chat.Android pull request #1962
Opened 2018-12-26 11:59 UTC by maryambehzi

@RocketChat/android

Closes #ISSUE_NUMBER

2018-12-26 11:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1962) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1962) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=1962) it.</sub>

2018-12-26 11:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1962) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1962) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=1962) it.</sub>

2018-12-26 15:04 UTC, philipbrito requested changes
There are strings to be removed or to add a comment indicating that it need to be translated.
Some strings don't need to be added here.
Check out the comments bellow please.

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="action_privacy_policy">Privacy Policy</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="msg_or_continue_using_social_accounts">Or continue using social accounts</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="msg_new_user_agreement">By proceeding you are agreeing to our\n%1$s and %2$s</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="msg_build" tools:ignore="MissingTranslation">Build %1$d - %2$s - %3$s</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

Also remove the `tools:ignore="MissingTranslation"`, please.

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="msg_update_app_version_in_order_to_continue">Out to date server version. Please contact the server admin to update the server version in order to continue.</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="msg_two_factor_authentication">Two-factor Authentication</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="msg__your_2fa_code">What’s your 2FA code?</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="msg_permalink_copied">Permalink copied</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="msg_send_analytics_tracking">Send anonymous statics to help improving this app</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="msg_do_not_send_analytics_tracking">Do not send anonymous statics to help improving this app</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="message_role_add">%1$s was set %2$s by %3$s</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="message_role_removed">%1$s is no longer %2$s by %3$s</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="max_file_size_exceeded">File size %1$d bytes exceeded max upload size of %2$d bytes</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="Show_the_keyboard_shortcut_list">Show the keyboard shortcut list</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="alert_title_default_skin_tone">Default skin tone</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="Displays_action_text">Displays action text</string>
Could you translate this string? If not, then could you add a `<!-- TODO Add translation -->` comment here?

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="status" translatable="false">Status</string>
You don't need to add this string here since it is not translatable.

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="foss" translatable="false">(FOSS)</string>
You don't need to add this string here since it is not translatable.

2018-12-26 15:04 UTC, philipbrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="msg_more_than_ninety_nine_unread_messages" translatable="false">99+</string>
You don't need to add this string here since it is not translatable.

2019-01-06 19:54 UTC, maryambehzi commented
I created a  new pull request with latest changes [here](https://github.com/RocketChat/Rocket.Chat.Android/pull/1985). Please merge that one.

2019-01-06 19:54 UTC, closed without merging