Added german translations to strings.xml
RocketChat/Rocket.Chat.Android pull request #1975
Opened 2018-12-28 00:33 UTC by Jan-NiklasB

@RocketChat/android

#### Changes: Added mutiple german translations

#### Screenshots or GIF for the change: -

2018-12-28 00:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1975) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=1975) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=1975) it.</sub>

2018-12-28 00:44 UTC, Jan-NiklasB commented
Faild checks don't seem to are directly related to the changes made...

2018-12-28 14:44 UTC, philipbrito requested changes

2018-12-28 14:44 UTC, filipedelimabrito commented on app/src/main/res/values-de/strings.xml
> +    <string name="msg_analytics_tracking">Google Analytics verfolgung</string>
Could you remove the `Google` here please?

2018-12-28 14:44 UTC, filipedelimabrito commented on app/src/main/res/values-de/strings.xml
> +    <string name="msg_continue_with_facebook">Mit <b>Facebook</b> einloggen</string>
Is `Mit` the translate to `Login` in English here? If so, could you translate it to the `Continue` in English?

2018-12-28 14:58 UTC, filipedelimabrito commented
@Jan-NiklasB It has failed because you send the PR to the `master` branch. It should be pointed to `develop`. I have changed it already. Could you fix the conflicts, please?

2018-12-28 17:53 UTC, Jan-NiklasB commented
Sure, I will do it as soon as I'm at home.

For the "mit" which means "with" I don't exactly know where this sentence is used so I translated it in a way that made the Most sence.
The Translation back to english would be " Login with FB" but in german the word by word translation doesn't makes much sence (which would be "Mit FB fortfahren") since continue or fortfahren has multiple meanings in german and would be Not very precise.

So you must decide how it should be translated... ;)

2018-12-28 18:56 UTC, filipedelimabrito commented
Perfect @Jan-NiklasB! Thanks for explaining (and teaching a little bit of German here). 
Taking advantage: Is `Analytics verfolgung` enough/good in German? If so let's only remove the `Google` word.

Thank you.

2018-12-28 18:58 UTC, filipedelimabrito commented
We'll be grateful if you fix the conflict here too. Thanks!

2018-12-28 19:53 UTC, Jan-NiklasB commented
@filipedelimabrito You're welcome :D 
I think for people who've no lingual relation to german like e.g. dutch or swiss german it's really hard to learn.
Especially the grammar xD (german grammar is sometimes very difficult, even for germans).

I changed the analytics string to "Daten für Analysezwecke" what means "data for analyzing purposes", I think that should be presice enougth for everyone.

2018-12-31 15:35 UTC, philipbrito approved these changes
Thanks a lot @Jan-NiklasB 💯

2018-12-31 15:35 UTC, merged