Improve Profile Layout according to a web interface
RocketChat/Rocket.Chat.Android pull request #2080
Opened 2019-03-02 03:26 UTC by arthurbdiniz

@RocketChat/android

Closes #2079

#### Changes: Create new style for EditTex and TextView on Profile Fragment. Adds username, email and name hint according to a web interface.

#### Screenshots or GIF for the change:
![app](https://user-images.githubusercontent.com/18387694/53676487-b4022d00-3c81-11e9-8d60-dc6840af1a7c.jpg)

2019-05-15 07:45 UTC, philipbrito requested changes

2019-05-15 07:45 UTC, filipedelimabrito commented on app/src/main/res/values/strings.xml
> +    <string name="msg_profile_username_hint" translatable="false">Please enter your username…</string>
Don't declare a translatable string as not translatable, please.

2019-05-15 07:45 UTC, filipedelimabrito commented on app/src/main/res/values/strings.xml
> +    <string name="msg_profile_name_hint" translatable="false">Please enter your name…</string>
Don't declare a translatable string as not translatable, please.

2019-05-15 07:45 UTC, filipedelimabrito commented on app/src/main/res/values/strings.xml
> +    <string name="msg_profile_email_hint" translatable="false">Please enter your email address…</string>
Don't declare a translatable string as not translatable, please.

2019-05-15 07:53 UTC, philipbrito requested changes

2019-05-15 07:53 UTC, filipedelimabrito commented on app/src/main/res/values/strings.xml
> +>>>>>>> dd938089e9ef495da5a5afd57651f611c1ad7bae
?

2019-05-15 07:57 UTC, philipbrito approved these changes
I've fixed the requested changes here.
Thanks for sending this PR.

2019-05-15 08:33 UTC, merged

2019-05-15 21:51 UTC, hfeky commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_gravity">left</item>
`layout_gravity` should be `start` instead of `left` to support RTL languages.

2019-06-04 18:33 UTC, filipedelimabrito commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_gravity">left</item>
Thanks for the catch @HusseinElFeky!

Changed!
https://github.com/RocketChat/Rocket.Chat.Android/commit/280f1c1ceca560f20f6045acc80f051b2a151e80