IMPROVEMENT Hide the drawing toolbar while drawing
RocketChat/Rocket.Chat.Android pull request #2084
Opened 2019-03-04 00:34 UTC by kareemhamdy100

@RocketChat/android

Closes #2066

#### Changes: add  button to toggle the toolbar and  add  onTouch.super(event)   in onTouch method so I could use  setOnClickListener on the drawing_area
#### Screenshots or GIF for the change:
![device-2019-03-04-022641](https://user-images.githubusercontent.com/28368419/53704465-80600800-3e25-11e9-8e18-29d0cf4053e3.gif)

2019-03-04 00:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2084) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2084) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=2084) it.</sub>

2019-03-04 00:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2084) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2084) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=2084) it.</sub>

2019-03-04 19:47 UTC, philipbrito requested changes

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                .show()
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +        if (showView)
Wrong code style.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +        if (view.translationY == (112).toPx && showView)
Wrong code style.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    ResourcesCompat.getColor(resources, R.color.color_red, null)
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    ResourcesCompat.getColor(
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            resources,
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            R.color.color_yellow, null
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    )
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    ResourcesCompat.getColor(
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            resources,
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            R.color.color_green, null
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    )
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    ResourcesCompat.getColor(resources, R.color.color_blue, null)
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    ResourcesCompat.getColor(
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            resources,
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            R.color.color_pink, null
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    )
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    )
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    ResourcesCompat.getColor(
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            resources,
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            R.color.color_brown, null
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    )
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    )
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    )
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    )
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            R.color.color_pink, null
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            resources,
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            R.color.color_pink, null
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    )
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                    ResourcesCompat.getColor(
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            resources,
Wrong formatting.

2019-03-04 19:47 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                            R.color.color_brown, null
Wrong formatting.

2019-03-04 22:44 UTC, kareemhamdy100 commented
@filipedelimabrito  I change the code format and code style 
what about the functionality is it good ?

2019-03-05 05:28 UTC, divyanshub024 commented
@kareemhamdy100 I see that you have added the `edit` button to show the drawing toolbar. It's better to hide the toolbar while drawing and show when you stop drawing. i.e when you lift your finger.

2019-03-05 10:45 UTC, kareemhamdy100 commented
@divyanshub024 I thinked in that way but found out that when lift your finger you can't see what you draw 
But I will try again

2019-05-15 02:36 UTC, philipbrito approved these changes
I have fixed some issues with the code formatting here.
Thank you very much for sending this PR @kareemhamdy100 
💯

2019-05-15 02:36 UTC, filipedelimabrito commented on draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
> +                ::toggleCompleteDrawTools)
`::toggleCompleteDrawTools` 👌

2019-05-15 02:38 UTC, merged