[NEW] Add Option to view user profile avatar in fullscreen
RocketChat/Rocket.Chat.Android pull request #2087
Opened 2019-03-04 21:30 UTC by GOVINDDIXIT

@RocketChat/android

Closes #2042 

#### Changes: 
User can view his profile picture on full screen
User can view profile pictures of other users on full screen

#### Screenshots or GIF for the change:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32304546/53764081-57f20f80-3ef2-11e9-9a2f-3f0a8000bd34.gif)

2019-04-18 19:03 UTC, philipbrito requested changes

2019-04-18 19:03 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
> +            fragmentManager?.beginTransaction()
You should move this code for our navigator class

2019-04-19 09:00 UTC, GOVINDDIXIT commented
@filipedelimabrito I have made the requested changes

2019-04-30 20:17 UTC, GOVINDDIXIT commented
@filipedelimabrito Pls review.  I have also updated the GIF

2019-06-26 23:19 UTC, philipbrito requested changes

2019-06-26 23:19 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
> +    fun toProfileImageDialog(avatarUrl: String) {
`toProfileImage` is enough - the "same" way we have declaring other functions here.

2019-06-26 23:19 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/main/presentation/MainNavigator.kt
> +    fun toProfileImageDialog(avatarUrl: String) {
`toProfileImage` is enough - the "same" way we have declaring other functions here.

2019-06-26 23:19 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
> +            val avatarUrl = presenter.getImageUri()
```
with(presenter) {
  toProfileImage(getImageUri())
}
```

2019-06-26 23:19 UTC, filipedelimabrito commented on app/src/main/res/layout/image_dialog_fragment.xml
> +    <com.facebook.drawee.view.SimpleDraweeView
Can we make use of the old and good `imageView` here? Then use it with `glide`

2019-06-27 08:54 UTC, GOVINDDIXIT commented
Hi @filipedelimabrito I have updated the PR with the requested changes, I have also added caching support and placeholder to the image. Pls review

2019-06-29 22:40 UTC, philipbrito requested changes

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
> +    fun getImageUri(): String {
Actually this function is useless.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/profile/ui/ImageDialogFragment.kt
> +fun newInstance(ImageUri: String): Fragment {
It's not an URI. It's an URL!

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/profile/ui/ImageDialogFragment.kt
> +        avatarUrl = ImageUri
It also answer my review above.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/profile/ui/ImageDialogFragment.kt
> +fun newInstance(ImageUri: String): Fragment {
Please do not capitalize variables!

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/profile/ui/ImageDialogFragment.kt
> +fun newInstance(ImageUri: String): Fragment {
Could you let us know why you instantiating it this way?

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/layout/fragment_user_details.xml
> +            android:id="@+id/user_image_avatar"
Please make sure to follow our coding style before changing the things! Wha's the reason to change the id of the imageView here?

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/userdetails/ui/UserDetailsFragment.kt
> +            .into(user_image_avatar)
Please make sure to follow our coding style before changing the things! Wha's the reason to change the id of the imageView here?

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/layout/image_dialog_fragment.xml
> +        android:id="@+id/detailImage"
Please make sure to follow our coding style when declaring the widget ids!

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/layout/image_dialog_fragment.xml
> +
Unnecessary blank line.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string>
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Add translation -->
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-uk/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Add translation -->
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-tr/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Add translation -->
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-ru-rRU/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Add translation -->
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Add translation -->
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-ja/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Add translation -->
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-it/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Add translation -->
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-hi-rIN/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Add translation -->
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-fr/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string>
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-fa/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Add translation -->
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-es/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Add translation -->
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-de/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Add translation -->
View profile photo instead.

2019-06-29 22:40 UTC, filipedelimabrito commented on app/src/main/res/values-ar/strings.xml
> +    <string name="action_view_profile_photo">View Profile photo</string><!-- TODO Translate -->
View profile photo instead.

2019-06-29 23:07 UTC, philipbrito approved these changes
The requested changes were fixed by me here. Thank you for sending this PR!

2019-06-29 23:14 UTC, merged