Changing search field width should be the max width
RocketChat/Rocket.Chat.Android pull request #2111
Opened 2019-03-08 01:38 UTC by AuraOfDivinity

@RocketChat/android

Closes #2045

#### Changes :Changed the search field width to be the max width when entering a query.

#### Screenshots or GIF for the change:
![lmao](https://user-images.githubusercontent.com/31003923/54001308-d9ef6c00-4170-11e9-88b9-d9439acc96af.png)

2019-03-08 16:07 UTC, philipbrito requested changes

2019-03-08 16:07 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> +private fun removeFavoriteMenuItem(menu: Menu){
Wrong formatting.

2019-03-08 16:07 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> +private fun removeDetailMenuItem(menu: Menu){
Wrong formatting.

2019-03-08 16:07 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> +
Unnecessary blank line.

2019-03-08 16:07 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> +
Unnecessary blank line.

2019-03-08 16:07 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> +
Unnecessary blank line.

2019-03-08 16:07 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> +
Unnecessary blank line.

2019-03-09 14:17 UTC, philipbrito requested changes
Could you fix the code formatting issues here?

2019-03-09 14:21 UTC, philipbrito requested changes

2019-03-09 14:21 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> +                chatRoomId,
Wrong indentation.

2019-03-09 14:21 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> +                chatRoomId,
Wrong indentation.

2019-03-09 14:21 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> +            Menu.NONE,
Wrong indentation.

2019-03-09 14:21 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> +                Menu.NONE,
Wrong indentation.

2019-03-09 14:21 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> +                Menu.NONE,
Wrong indentation.

2019-03-11 08:30 UTC, GOVINDDIXIT reviewed
Pls make sure that the tests passes

2019-03-11 08:30 UTC, GOVINDDIXIT commented on app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
> -            Menu.NONE,
formatting issue

2019-03-11 12:01 UTC, philipbrito approved these changes
Thank you very much for sending this PR @AuraOfDivinity!
💯

2019-03-11 12:02 UTC, merged