Implemented swipe to reply message.
RocketChat/Rocket.Chat.Android pull request #2212
Opened 2019-04-09 11:54 UTC by Adizbek

@RocketChat/android

#### Changes: Added swipe to reply functionality.

#### Screenshots or GIF for the change:
https://youtu.be/lD3xU6pBWEk

2019-04-15 13:10 UTC, philipbrito requested changes

2019-04-15 13:10 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +import chat.rocket.android.chatroom.adapter.*
Avoid using wildcard import.

2019-04-15 13:10 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +                    citeMessage(chatRoomName, chatRoomType, viewHolder.data?.messageId!!, true)
Avoid using `!!`

2019-04-15 13:16 UTC, Adizbek commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +import chat.rocket.android.chatroom.adapter.*
I'll fix them today.

2019-04-21 06:26 UTC, Adizbek commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +                    citeMessage(chatRoomName, chatRoomType, viewHolder.data?.messageId!!, true)
Fixed

2019-04-28 13:19 UTC, Adizbek commented
@filipedelimabrito Can you review?

2019-05-14 23:43 UTC, philipbrito approved these changes
Thanks for sending this PR @Adizbek!
💯

2019-05-15 00:00 UTC, merged