[FIX] Typos and Translation Mistakes
RocketChat/Rocket.Chat.Android pull request #2214
Opened 2019-04-09 15:37 UTC by HusseinElFeky

@RocketChat/android

#### Changes:

This pull request brings some fixes to typos, sentence structure and translation mistakes.

1. Changed Github to GitHub
2. Changed Gitlab to GitLab
3. Changed Linkedin to LinkedIn
4. Changed Wordpress to WordPress
5. Replaced the string resource name `msg_forgot__your_password` with `msg_forgot_your_password`
6. Added a missing question mark in `msg_delete_description` string resource in some translations
7. Fixed some Arabic translation mistakes
8. Fixed question mark direction in some strings in Arabic and Persian strings resource files
9. Translated 4 strings in Spanish strings resource file
10. Changed statics to statistics and improving to improve in preferences messages section in the default strings resource file

2019-04-15 13:05 UTC, filipedelimabrito commented
@HusseinElFeky Could you fix the conflicts here?

2019-04-16 11:41 UTC, HusseinElFeky commented
@filipedelimabrito I have merged the branches. Please check if any further change is required.

2019-04-18 15:13 UTC, philipbrito requested changes

2019-04-18 15:13 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
> +import android.view.*
@HusseinElFeky Could you remove this wildcard import, please?

2019-04-18 19:11 UTC, HusseinElFeky commented
@filipedelimabrito I removed the wildcard import. Thanks for pointing it out.

2019-04-18 20:09 UTC, philipbrito approved these changes
Thank you very much for making it @HusseinElFeky 💯

2019-04-18 20:23 UTC, merged