Implemented sort chats by unread on top.
RocketChat/Rocket.Chat.Android pull request #2263
Opened 2019-04-26 03:31 UTC by NBAMIR

@RocketChat/android

Closes #2254 

#### Changes: 
Implemented sorting option unread on top to work with sort by name, by activity and by group type.

2019-04-26 08:14 UTC, divyanshub024 commented
@NBAMIR There is a conflict. Can you resolve it?

2019-04-26 09:15 UTC, NBAMIR commented
Thank you for pointing it out. I'll look into it!

2019-04-26 14:34 UTC, philipbrito requested changes

2019-04-26 14:34 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
> +            viewModel.setQuery(Query.ByName(isGroupByType,isUnreadOnTop))
Attempt to the code formatting: Add a space after the comma.

2019-04-26 14:34 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
> +            viewModel.setQuery(Query.ByActivity(isGroupByType,isUnreadOnTop))
Attempt to the code formatting: Add a space after the comma.

2019-04-26 14:34 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
> +            viewModel.setQuery(Query.ByName(isGroupByType,isUnreadOnTop))
Attempt to the code formatting: Add a space after the comma.

2019-04-26 14:34 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/infrastructure/ChatRoomsRepository.kt
> +            Order.UNREADONTOP_ACTIVITY -> dao.getAllUnread();
`UNREAD_ON_TOP` instead of `UNREADONTOP` is better.

2019-04-26 14:34 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
> +    data class ByName(val grouped: Boolean = false,val unreadOnTop: Boolean = false ) : Query()
Attempt to the code formatting: Add a space after the comma - as you did above.

2019-04-28 23:19 UTC, philipbrito requested changes
@NBAMIR Could you please fix the errors here?

2019-04-28 23:19 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
> +                ChatRoomsRepository.Order.UNREADONTOP_NAME
It won't compile! 

 Unresolved reference.

2019-04-28 23:19 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
> +                ChatRoomsRepository.Order.UNREADONTOP_GROUPED_NAME
It won't compile! 

 Unresolved reference.

2019-04-28 23:19 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
> +                ChatRoomsRepository.Order.UNREADONTOP_ACTIVITY
It won't compile! 

 Unresolved reference.

2019-04-28 23:19 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
> +                ChatRoomsRepository.Order.UNREADONTOP_GROUPED_ACTIVITY
It won't compile! 

 Unresolved reference.

2019-04-29 16:09 UTC, philipbrito approved these changes
Thank you very much for sending it @NBAMIR!
💯

2019-04-29 17:55 UTC, merged