Fix for #2313 Message search results (@mentions) do not have any date indication in the results
RocketChat/Rocket.Chat.Android pull request #2320
Opened 2019-05-16 05:47 UTC by sudipt1999

Please review the changes ! Now I am showing full date `Hr:Min Month Day, Year` kindly cross check. 
Actual link of issue https://github.com/WideChat/Rocket.Chat.Android/issues/337

2019-05-16 05:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2320) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2320) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=2320) it.</sub>

2019-05-16 05:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2320) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2320) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=2320) it.</sub>

2019-05-17 15:44 UTC, ear-dev commented
@sudipt1999 I built this, but I'm getting an error message each time I try to open a chatroom.... any ideas?

05-17 11:37:16.731 17727-17727/chat.rocket.android.dev E/ChatRoomPresenter$loadMessages: org.threeten.bp.DateTimeException: Unable to extract value: class org.threeten.bp.LocalDateTime
        at org.threeten.bp.format.DateTimePrintContext.getValue(DateTimePrintContext.java:258)
        at org.threeten.bp.format.DateTimeFormatterBuilder$ZoneTextPrinterParser.print(DateTimeFormatterBuilder.java:3362)
        at org.threeten.bp.format.DateTimeFormatterBuilder$CompositePrinterParser.print(DateTimeFormatterBuilder.java:1995)
        at org.threeten.bp.format.DateTimeFormatterBuilder$LocalizedPrinterParser.print(DateTimeFormatterBuilder.java:3751)
        at org.threeten.bp.format.DateTimeFormatterBuilder$CompositePrinterParser.print(DateTimeFormatterBuilder.java:1995)
        at org.threeten.bp.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1385)
        at org.threeten.bp.format.DateTimeFormatter.format(DateTimeFormatter.java:1359)
        at org.threeten.bp.chrono.ChronoLocalDateTime.format(ChronoLocalDateTime.java:263)
        at org.threeten.bp.LocalDateTime.format(LocalDateTime.java:1828)
        at DateTimeHelper.getTime(DateTimeHelper.kt:69)
        at chat.rocket.android.chatroom.uimodel.UiModelMapper.getTime(UiModelMapper.kt:535)
        at chat.rocket.android.chatroom.uimodel.UiModelMapper.access$getTime(UiModelMapper.kt:56)
        at chat.rocket.android.chatroom.uimodel.UiModelMapper$mapMessage$2.invokeSuspend(UiModelMapper.kt:443)
        at chat.rocket.android.chatroom.uimodel.UiModelMapper$mapMessage$2.invoke(Unknown Source:33)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:146)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at chat.rocket.android.chatroom.uimodel.UiModelMapper.mapMessage(UiModelMapper.kt:441)
        at chat.rocket.android.chatroom.uimodel.UiModelMapper$translate$2.invokeSuspend(UiModelMapper.kt:143)
        at chat.rocket.android.chatroom.uimodel.UiModelMapper$translate$2.invoke(Unknown Source:33)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:146)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at chat.rocket.android.chatroom.uimodel.UiModelMapper.translate(UiModelMapper.kt:124)
        at chat.rocket.android.chatroom.uimodel.UiModelMapper$map$4.invokeSuspend(UiModelMapper.kt:97)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

2019-05-18 16:08 UTC, sudipt1999 commented
![current](https://user-images.githubusercontent.com/38929617/57972235-437fc800-79b5-11e9-9b47-e2bf61e3b7b0.jpg)


Current changes!

2019-05-20 16:18 UTC, jaytat0 commented
@sudipt1999 I don't believe this addresses what the initial issue was intending to get fixed (https://github.com/WideChat/Rocket.Chat.Android/issues/337), which is that when you look at the screenshot from that: 
![image](https://user-images.githubusercontent.com/8495373/58036159-71b9f080-7af8-11e9-9b62-de4a32597745.png)
What's showing are the results of a search for "bulls". But a user has no way of knowing what date those search results are from. So what's needed is a date indication for search results, and the same applies for @mentions.

I don't believe that the "today" change is needed. Once date indicators are put in properly, a result  from a year ago will have the year showing  ("May 20, 2018") so it won't be confused with today.

2019-05-21 22:17 UTC, hfeky requested changes

2019-05-21 22:17 UTC, HusseinElFeky commented on app/src/main/java/chat/rocket/android/app/DateTimeHelper.kt
> +            today -> "Today " + formatLocalTime(localDateTime.toLocalTime())
Please avoid using hardcoded strings. Add that to strings resource files for all languages.

2019-06-02 17:31 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/app/DateTimeHelper.kt
> +        if(isSearching){
Make sure to follow our coding style.

2019-06-03 13:54 UTC, filipedelimabrito commented
@sudipt1999 Are you going to make changes here based on the comments done by @jaytat0 ?

2019-06-03 15:37 UTC, sudipt1999 commented
@filipedelimabrito yes sir changes are already made for that! As you mentioned to change the coding style will do that today.

2019-06-05 11:14 UTC, sudipt1999 commented
@filipedelimabrito Please review the pr.

2019-06-26 22:16 UTC, philipbrito requested changes

2019-06-26 22:16 UTC, philipbrito commented on app/src/main/java/chat/rocket/android/app/DateTimeHelper.kt
> +        if (isSearching) {
The logic here could be improved in more that one way.

1 - You could make the return lifted out of if.
2 - If you are searching you don't need to have the formatter variable on the top.

2019-06-26 22:16 UTC, philipbrito commented on app/src/main/java/chat/rocket/android/app/DateTimeHelper.kt
> +    var isSearching = false
You can make it working without declaring it, this way you could also avoid creating a new function here.

2019-06-26 22:33 UTC, philipbrito approved these changes
Code improvement will be addressed by this PR: https://github.com/RocketChat/Rocket.Chat.Android/pull/2390

Thanks for sending this one!

2019-06-26 22:41 UTC, merged