[NEW] Add support for hardcoded server URL
RocketChat/Rocket.Chat.Android pull request #2384
Opened 2019-06-19 21:49 UTC by cardoso

@RocketChat/android

Closes #2177 

#### Changes: 

- Adds RC_SERVER_URL to build configs
- Connects automatically to server set in build configs
- Disables chang server/add server modal if RC_SERVER_URL is set

2019-06-19 21:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2384) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2384) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=2384) it.</sub>

2019-06-19 21:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2384) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2384) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=2384) it.</sub>

2019-06-21 02:47 UTC, philipbrito requested changes

2019-06-21 02:47 UTC, filipedelimabrito commented on app/build.gradle
> +            buildConfigField "String", "RC_SERVER_URL", '""'
Move to `defaults.xml` file please. 

string tag can be just `server_url` there.

2019-06-21 02:47 UTC, filipedelimabrito commented on app/build.gradle
> +            buildConfigField "String", "RC_SERVER_URL", '""'
After moving you don't need even to declare it here.

2019-06-21 02:47 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
> +            if (BuildConfig.RC_SERVER_URL != "") {
Checking if a string is not empty? Use `.isNotEmpty()`.

2019-06-21 02:47 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/authentication/ui/AuthenticationActivity.kt
> +                } else if (BuildConfig.RC_SERVER_URL == "") {
Checking if a string is not empty? Use `.isNotEmpty()`.

2019-06-21 02:47 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
> +        if (BuildConfig.RC_SERVER_URL == "") {
Checking if a string is not empty? Use `.isNotEmpty()`.

2019-06-21 02:47 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
> +                        activity?.supportFragmentManager,
Wrong indentation. Please make sure to follow our coding style.

2019-06-25 15:23 UTC, cardoso commented
Thanks for your review @filipedelimabrito . I've updated the code accordingly.

2019-06-25 19:28 UTC, philipbrito approved these changes

2019-06-25 19:28 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
> +                    activity?.supportFragmentManager,
Thank you very much for sending this PR @cardoso! I'm glad to see you here.

Just a tip: `chat.rocket.android.servers.ui.TAG` fits on the same line where `activity?.supportFragmentManager` is declared here - respecting the coding style. But it's fine!

Thank you! 👊

2019-06-25 19:30 UTC, merged