add loading bar when loading avatar image and other info in settings
RocketChat/Rocket.Chat.Android pull request #2429
Opened 2019-07-25 21:55 UTC by weijia-yu

@RocketChat/android

Closes #2357 

#### Changes: 

Add loading bar if it is loading the data

#### Screenshots or GIF for the change:

![loading](https://user-images.githubusercontent.com/3372754/61911409-3f5bb380-aeec-11e9-9a09-8fed2b290c14.gif)

2019-07-25 21:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2429) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=2429) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=2429) it.</sub>

2019-07-26 20:03 UTC, filipedelimabrito commented
@weijia-yu Would be great if we hide all the screen information (because we can still see the placeholders for some text) and show it when it is really ready to de displayed. Could you do that?

2019-07-26 22:36 UTC, weijia-yu commented
@filipedelimabrito you mean basically showing a blank screen before all info shows up? If in that case, what if the loading fails, would it show an error dialogue?

2019-07-29 09:32 UTC, filipedelimabrito commented
@weijia-yu I mean doing the same we do on the chat list: It has nothing except the toolbar and navigation bar and our loading view. When the chat list is ready to be presented to the users we hide the loading and show that list. If something fails we will show a toast (actually I believe we are doing it already).

2019-08-19 13:44 UTC, philipbrito requested changes

2019-08-19 13:44 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/settings/presentation/SettingsPresenter.kt
> +                view.hideLoading()
Not needed to call `hideLoading()` two times here. You can call it on the `finally {...}` block just one time instead.

2019-08-19 15:01 UTC, philipbrito approved these changes
@weijia-yu I've fixed the requested changes here! Thanks for sending this PR!

2019-08-19 15:01 UTC, merged