fix lost text when turn off then turn on screen
RocketChat/Rocket.Chat.Android pull request #260
Opened 2017-04-23 15:47 UTC by congnt24

fix lost text when turn off then turn on screen, hide keyboard when change room chat

@RocketChat/android

Closes #256

2017-04-23 15:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=260) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=260) before we can accept your contribution.<br/><hr/>**Nguyen Cong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=260) it.</sub>

2017-04-24 16:24 UTC, laggedHero requested changes

2017-04-24 16:24 UTC, laggedHero commented on app/src/main/java/chat/rocket/android/activity/MainActivity.java
> +//      presenter.release();
This is really bad since we'll not clean up the subscriptions made. I can't accept this change.

2017-04-24 16:24 UTC, laggedHero commented on app/src/main/java/chat/rocket/android/activity/AbstractAuthedActivity.java
> +    ConnectivityManager.getInstance(getApplicationContext()).keepAliveServer();
Let's put this back into the `onResume`. It's trying to keep the connection alive.

2017-05-01 09:17 UTC, congnt24 commented
The problem is that whenever onResume() call, it will recreate a new RoomFragment and the state of fragment will lose, not just text in EditText. I already changed some code that you requested. Please review.

2017-05-03 18:48 UTC, geekgonecrazy commented on app/src/main/java/chat/rocket/android/activity/MainActivity.java
> +    KeyboardHelper.hideSoftKeyboard(this);
Looks like might have a comment that needs removed.  The line right below seems to be doing exactly what the TODO calls for :)

2017-05-03 19:06 UTC, laggedHero commented
There's still some rough edges... but the code here, in general, is kind of rough.

Let's remove that comment and merge it in.

2017-05-04 07:57 UTC, congnt24 commented
I've removed comment

2017-05-04 13:53 UTC, laggedHero approved these changes

2017-05-04 16:44 UTC, laggedHero commented
Hmm, I'll check the build here.

2017-05-04 16:44 UTC, merged