UX/UI Improvements/Adjustments
RocketChat/Rocket.Chat.Android pull request #364
Opened 2017-07-26 20:04 UTC by filipedelimabrito

@RocketChat/android

This updates the attach icon, send icon and add a scroll indicator

![videotogif_2017 07 26_16 55 37](https://user-images.githubusercontent.com/11776825/28641013-0a838b3a-7224-11e7-9770-254936fc237d.gif)

2017-07-26 22:58 UTC, rafaelks commented
Nice touch @filipedelimabrito! 👍 🚀

2017-07-27 13:34 UTC, rafaelks approved these changes

2017-07-27 13:38 UTC, luciofm requested changes
Just some styling issues

2017-07-27 13:38 UTC, luciofm commented on rocket-chat-android-widgets/src/main/res/layout/message_composer.xml
> +<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Can you reformat it following the new code style (https://github.com/RocketChat/Rocket.Chat.Android/blob/develop/CONDING_STYLE.md)?

2017-07-27 13:38 UTC, luciofm commented on rocket-chat-android-widgets/src/main/res/values/colors.xml
> +<?xml version="1.0" encoding="utf-8"?>
This one also

2017-07-27 20:31 UTC, filipedelimabrito commented on rocket-chat-android-widgets/src/main/res/layout/message_composer.xml
> +<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Of course! Already done! :)

2017-07-27 20:31 UTC, filipedelimabrito commented on rocket-chat-android-widgets/src/main/res/values/colors.xml
> +<?xml version="1.0" encoding="utf-8"?>
Done @luciofm !

2017-07-27 21:06 UTC, luciofm approved these changes
Thanks :)

2017-07-27 21:09 UTC, luciofm requested changes
The build is broken...

```
:rocket-chat-android-widgets:compileReleaseJavaWithJavac
:rocket-chat-android-widgets:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/home/travis/build/RocketChat/Rocket.Chat.Android/rocket-chat-android-widgets/src/main/java/chat/rocket/android/widget/message/MessageFormLayout.java:167: error: cannot find symbol
    composer.findViewById(R.id.sendImageButton).setEnabled(enabled);
                              ^
  symbol:   variable sendImageButton
  location: class id
```

2017-07-27 21:30 UTC, luciofm approved these changes

2017-07-27 21:30 UTC, merged