#331 - Display Keyboard when launching dialog.
RocketChat/Rocket.Chat.Android pull request #500
Opened 2017-10-03 08:06 UTC by HarveyDoom

First ever pull request.
requestFocus() would not work on its own. Setting the Soft Input Mode gets keyboard to display.

@RocketChat/android

Closes #ISSUE_NUMBER

2017-10-03 08:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=500) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=500) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=500) it.</sub>

2017-10-03 21:00 UTC, filipedelimabrito commented
Hi @HarveyDoom!

In order to merge your PR you need to fix a few thinga. Here is a tip:

- Import the `WindowManager` class to use [here](https://github.com/HarveyDoom/Rocket.Chat.Android/blob/a1534394ddda689ff25a75441b70872b5a2678c0/app/src/main/java/chat/rocket/android/fragment/sidebar/dialog/AbstractAddRoomDialogFragment.java#L47).
- Import the `TextInputEditText` class to use [here](https://github.com/HarveyDoom/Rocket.Chat.Android/blob/a1534394ddda689ff25a75441b70872b5a2678c0/app/src/main/java/chat/rocket/android/fragment/sidebar/dialog/AddChannelDialogFragment.java#L42).

2017-10-03 21:01 UTC, philipbrito requested changes
Hi @HarveyDoom!

In order to merge your PR you need to fix a few things. Here is a tip:

- Import the `WindowManager` class to use [here](https://github.com/HarveyDoom/Rocket.Chat.Android/blob/a1534394ddda689ff25a75441b70872b5a2678c0/app/src/main/java/chat/rocket/android/fragment/sidebar/dialog/AbstractAddRoomDialogFragment.java#L47).
- Import the `TextInputEditText` class to use [here](https://github.com/HarveyDoom/Rocket.Chat.Android/blob/a1534394ddda689ff25a75441b70872b5a2678c0/app/src/main/java/chat/rocket/android/fragment/sidebar/dialog/AddChannelDialogFragment.java#L42).

2017-10-12 00:18 UTC, leonardoaramaki approved these changes
@HarveyDoom Thank you a lot for your contribution! 
Sorry for the long time gap to review this one.
Merging!

2017-10-12 00:19 UTC, merged