Add resources for Russian language
RocketChat/Rocket.Chat.Android pull request #629
Opened 2017-12-10 21:47 UTC by Sveer

@RocketChat/android
Add resources for Russian language (app & widget):
![screenshot_2017-12-11-00-42-52-670_chat rocket android](https://user-images.githubusercontent.com/4079141/33809753-d97bc976-de0c-11e7-9626-009ea6707567.png)
![screenshot_2017-12-11-00-45-32-166_chat rocket android](https://user-images.githubusercontent.com/4079141/33809756-e008a106-de0c-11e7-9b0d-8b5eb99d87f7.png)

2017-12-10 21:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=629) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=629) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=629) it.</sub>

2017-12-11 10:46 UTC, rafaelks commented
LGTM! Thank you @Sveer!

2017-12-11 10:47 UTC, rafaelks approved these changes

2017-12-12 19:51 UTC, leonardoaramaki requested changes

2017-12-12 19:51 UTC, leonardoaramaki commented on app/src/main/res/values-ru/strings.xml
> +    <string name="fragment_room_list_pinned_message_title">Закрепленные сообщения (%с)</string>
@Sveer Thanks for contributing!
Does this formatter qualifier `(%с)` working for you? Here this crashes the app.

2017-12-12 21:42 UTC, Sveer commented on app/src/main/res/values-ru/strings.xml
> +    <string name="fragment_room_list_pinned_message_title">Закрепленные сообщения (%с)</string>
Ou.. Sorry :( Will fix.

2017-12-12 23:44 UTC, leonardoaramaki approved these changes
Thanks @Sveer!

2017-12-12 23:44 UTC, merged