[IMPROVEMENT] Adds error messages to sign up dialog edit texts
RocketChat/Rocket.Chat.Android pull request #658
Opened 2017-12-24 10:28 UTC by aniketsingh03

@RocketChat/android

Closes #641 

This will be a minor improvement in the ux of the app.

2017-12-24 17:30 UTC, saketkumar requested changes
Nice work @aniketsingh03 👍 
Left some comments!

2017-12-24 17:30 UTC, saketkumar95 commented on app/src/main/java/chat/rocket/android/fragment/server_config/UserRegistrationDialogFragment.java
> +    private String password;
1 line space should be required here to separate other object variables.

2017-12-24 17:30 UTC, saketkumar95 commented on app/src/main/java/chat/rocket/android/fragment/server_config/UserRegistrationDialogFragment.java
> +    private View waitingView;
Here too!

2017-12-26 22:39 UTC, leonardoaramaki approved these changes

2017-12-26 22:40 UTC, merged