[BUG] Orientation Change on ProfileFragment Fix
RocketChat/Rocket.Chat.Android pull request #831
Opened 2018-03-01 16:49 UTC by SyamSundarKirubakaran

@RocketChat/android

Closes #824 

![pr 2](https://user-images.githubusercontent.com/26897680/36857402-7801ad88-1d9e-11e8-8aa6-fa6835bd4b9b.gif)

2018-03-01 20:18 UTC, filipedelimabrito commented
Thanks for your contribution @SyamSundarKirubakaran !
We'll review it late!
Thank you!

2018-03-30 02:34 UTC, rafaelks commented
@SyamSundarKirubakaran Orientation is working for me, but the screen doesn't scroll, so I'm not able to see all the fields on my screen completely. Do you mind adding a scroll view on this screen also?

2018-04-03 01:21 UTC, SyamSundarKirubakaran commented
@rafaelks I've resolved some merge conflicts and added a scroll view. Sorry for the delayed commit, was a bit held up. Thanks.

2018-04-30 17:43 UTC, philipbrito requested changes

2018-04-30 17:43 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
> +    private var CURRENT_STATE: String = "CURRENT_STATE"
It's supposed to be a `const`, so declare it as such.

2018-06-05 15:29 UTC, filipedelimabrito commented
Closing this PR since it is already fixed.

2018-06-05 15:29 UTC, closed without merging