No pinned message shown on empty pin List
RocketChat/Rocket.Chat.Android pull request #930
Opened 2018-03-15 23:10 UTC by divyanshub024

@RocketChat/android

Closes #895 

This PR will show "No pinned message" on empty List.

![device-2018-03-16-043829](https://user-images.githubusercontent.com/16731434/37495628-1637e842-28d4-11e8-976d-0c8adc34f640.png)

2018-03-15 23:34 UTC, aniketsingh03 commented
@divyanshub024 looks good, but I feel that this and [#931](https://github.com/RocketChat/Rocket.Chat.Android/pull/931) should be similar in terms of icon size, color and text color, so we need to decide upon a common pattern for them. @rafaelks @leonardoaramaki can you guys tell us what size and color would be appropriate for these cases?

2018-03-20 21:55 UTC, philipbrito requested changes

2018-03-20 21:55 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/PinnedMessagesFragment.kt
> +         iv_pin_icon.visibility = View.VISIBLE
Change `iv_pin_icon.visibility = View.VISIBLE` to `iv_pin_icon.setVisible(true)` - as well as for the others.

2018-03-20 21:55 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/PinnedMessagesFragment.kt
> +         iv_pin_icon.visibility = View.GONE
Change `iv_pin_icon.visibility = View.VISIBLE` to `iv_pin_icon.setVisible(false)` - as well as for the others.

2018-03-20 21:55 UTC, filipedelimabrito commented on app/src/main/res/values/strings.xml
> +    <string name="no_pinned_description">All the pinned messages   appear here.</string>
There are white spaces in this sentence.

2018-03-20 21:55 UTC, filipedelimabrito commented on app/src/main/res/values/strings.xml
> +    <string name="no_pinned_messages">No pinned Messages</string>
Please, could you start the `Messages` in lowercase?

2018-03-20 21:55 UTC, filipedelimabrito commented on app/src/main/res/values/strings.xml
> +    <string name="no_pinned_messages">No pinned Messages</string>
Could you add the Brazilian translation for this string?

No pinned Messages -> Nenhuma mensagem pinada.

2018-03-20 21:55 UTC, filipedelimabrito commented on app/src/main/res/values/strings.xml
> +    <string name="no_pinned_description">All the pinned messages   appear here.</string>
Could you add the Brazilian translation for this string?

All the pinned messages appear here -> Todas as mensagens pinadas aparecerão aqui.

2018-03-21 14:52 UTC, divyanshub024 commented
@filipedelimabrito all changes are made. Pls review it

2018-04-10 08:52 UTC, rafaelks commented
@divyanshub024 Did you delete your branch? Cannot find the branch anymore here to update it.

2018-04-10 09:31 UTC, divyanshub024 commented
@rafaelks sorry! It was a mistake. I'll create a new PR.

2018-04-10 13:34 UTC, divyanshub024 commented
clone #1066

2018-04-10 13:34 UTC, closed without merging