[NEW] Display a view in a chat room in case a it has no chats
RocketChat/Rocket.Chat.Android pull request #931
Opened 2018-03-15 23:18 UTC by aniketsingh03

@RocketChat/android

Closes https://github.com/RocketChat/Rocket.Chat.Android/issues/896

2018-03-17 12:49 UTC, aniketsingh03 commented
@leonardoaramaki can you provide a drawable and information regarding its size and color of the text for this?

2018-03-19 18:02 UTC, leonardoaramaki commented
@aniketsingh03 The drawable is on the line to be done by the design team but it's not prioritized. We'll have to wait

2018-03-20 21:47 UTC, philipbrito requested changes

2018-03-20 21:47 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +        no_messages_view.visibility = View.VISIBLE
You can use the `no_messages_view.setVisible(true)` here.

2018-03-20 21:47 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +        no_messages_view.visibility = View.GONE
`no_messages_view.setVisible(false)`

2018-03-20 21:47 UTC, filipedelimabrito commented on app/src/main/res/values/strings.xml
> +    <string name="msg_no_chats_available">There are no messages yet in this channel</string>
There are no messages yet in this channel -> There are no messages in this channel yet.

For Brazilian translation:
Não há mensagens neste canal ainda.

2018-03-20 21:47 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
> +                initialiseRecyclerViewAdapter()
Great! 👍

2018-03-21 00:36 UTC, aniketsingh03 commented
@filipedelimabrito I have made the requested changes

2018-03-27 17:34 UTC, aniketsingh03 commented
@leonardoaramaki is the drawable ready?

2018-04-05 23:12 UTC, aniketsingh03 commented
@leonardoaramaki @rafaelks @filipedelimabrito I have resolved some fresh conflicts, I can add the drawable if its ready.

2018-04-27 13:42 UTC, closed without merging