show msg in empty recent emoji picker
RocketChat/Rocket.Chat.Android pull request #946
Opened 2018-03-20 14:52 UTC by divyanshub024

@RocketChat/android

Closes #897 

This PR will show "No recent emoji" msg in recent emoji picker.
![device-2018-03-20-201829](https://user-images.githubusercontent.com/16731434/37662125-5cc2dab4-2c7c-11e8-965e-36874f9293d4.png)

2018-03-20 21:33 UTC, filipedelimabrito commented
Could you fix the conflict file @divyanshub024 ?

2018-03-20 21:40 UTC, philipbrito requested changes

2018-03-20 21:40 UTC, filipedelimabrito commented on app/src/main/res/layout/emoji_category_layout.xml
> +        android:id="@+id/tv_recent_emoji"
Change the `tv_recent_emoji` to `text_no_recent_emoji`. This will be more meaningful (and will follow our code style).

2018-03-20 21:40 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/widget/emoji/CategoryPagerAdapter.kt
> +            tv_recent_emoji.visibility = View.VISIBLE
You can use `tv_recent_emoji.setVisible(true/false)` here.

2018-03-20 21:40 UTC, filipedelimabrito commented on app/src/main/res/values/strings.xml
> +    <string name="msg_no_recent_emoji">No recent emoji</string>
Add the following string for Brazilian translation:

`<string name="msg_no_recent_emoji">Nenhum emoji recente</string>`

Thanks.

2018-03-21 06:52 UTC, divyanshub024 commented
@filipedelimabrito all requested changes are done.

2018-03-26 15:53 UTC, leonardoaramaki requested changes

2018-03-26 15:53 UTC, leonardoaramaki commented on app/src/main/java/chat/rocket/android/widget/emoji/CategoryPagerAdapter.kt
> +        val text_no_recent_emoji : TextView = view.findViewById(R.id.text_no_recent_emoji)
Please no snakecase here. Parts of the codebase where we see snakecase named variables is that it comes from the `kotlin-android-extensions` plugin.

2018-03-26 17:05 UTC, divyanshub024 commented on app/src/main/java/chat/rocket/android/widget/emoji/CategoryPagerAdapter.kt
> +        val text_no_recent_emoji : TextView = view.findViewById(R.id.text_no_recent_emoji)
Should I change it to `emojiRecentText`

2018-03-26 17:06 UTC, leonardoaramaki commented on app/src/main/java/chat/rocket/android/widget/emoji/CategoryPagerAdapter.kt
> +        val text_no_recent_emoji : TextView = view.findViewById(R.id.text_no_recent_emoji)
:+1:

2018-03-26 17:11 UTC, divyanshub024 commented
@leonardoaramaki I have made the changes.

2018-03-26 17:13 UTC, leonardoaramaki approved these changes

2018-03-26 17:13 UTC, leonardoaramaki commented
Thanks!

2018-03-26 17:14 UTC, merged

2018-03-27 09:02 UTC, antgel commented
Would be great to rebase to fix conflicts rather than add merge commits.