Web preview customtabs
RocketChat/Rocket.Chat.Android pull request #967
Opened 2018-03-28 19:25 UTC by ear-dev

@RocketChat/android

This fixes two bugs we found in regard to using custom tabs when clicking links in a chat window. 
 
1) Clicking web preview links resulted in opening a webView and not a custom tab.  It now opens a custom tab. 
2) A capital 'H' in Http://www.**.com urls would cause the app to crash.  This PR converts to lower case before passing to custom tabs.
3) The PR also contains a small refactor to implement a dependency correctly.

2018-03-28 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=967) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Android?pullRequest=967) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Android?pullRequest=967) it.</sub>

2018-03-28 19:36 UTC, philipbrito approved these changes
Thanks!

2018-03-28 19:36 UTC, filipedelimabrito commented on app/build.gradle
> +    implementation libraries.customTabs
Thanks for this change.

2018-03-28 19:36 UTC, filipedelimabrito commented on dependencies.gradle
> +        customTabs             : '27.0.2',
Thanks again.

2018-03-28 19:36 UTC, filipedelimabrito commented on dependencies.gradle
> +        customTabs             : "com.android.support:customtabs:${versions.customTabs}",
Thanks again.

2018-03-28 19:36 UTC, filipedelimabrito commented on app/src/main/java/chat/rocket/android/chatroom/adapter/UrlPreviewViewHolder.kt
> +                customTabsIntent.launchUrl(context, Uri.parse(data.rawData.url.toLowerCase()))
You can use `data.rawData.url.toLowerCase().toUri`.

Fresh from Android KTX -> https://android.github.io/android-ktx/core-ktx/androidx.net/kotlin.-string/to-uri.html.

2018-03-28 20:25 UTC, philipbrito requested changes
Only a small change and thanks!

2018-03-28 20:25 UTC, filipedelimabrito commented on dependencies.gradle
> +        customTabs             : '27.0.2',
You don't need to specify it here. CustomTabs uses Support Library, so remove it and use 
https://github.com/WideChat/Rocket.Chat.Android/blob/18aa1d623afaf721b2108f694ef720f4db4f5faf/dependencies.gradle#L12

2018-03-29 02:55 UTC, Shailesh351 commented
@ear-dev I don't think converting url to lower case is good fix, it can break url. Some url have uniqe ids which have uppercase letters also(like google drive sharing link)

2018-03-29 17:44 UTC, leonardoaramaki commented
@Shailesh351 is right. You should do `HttpUrl.parse().host().toLowerCase()` on the host only and then append the rest of the string. It's a very weird bug on custom tabs. What you could also do is  `HttpUrl.parse().schema().toLowerCase()`. Haven't tested but I think what's breaking is just the schema. Then you concatenate the rest of the url. `HttpUrl` can help you with that.

2018-03-29 21:58 UTC, philipbrito approved these changes

2018-03-29 22:00 UTC, filipedelimabrito commented
@ear-dev Just do the changes requested/appointed by @Shailesh351 and @leonardoaramaki and done.

2018-03-30 18:34 UTC, ear-dev commented
@Shailesh351 @filipedelimabrito @leonardoaramaki It took me a while to figure out how to use HttpUrl, not to mention that I am also new to Java, but I have a fix for only lower casing the scheme.  I put the method in a helper file and I just guessed as to a relevant location for that file.  I tested all scenarios that we know about, so this worked.  Thanks!

2018-04-01 15:25 UTC, leonardoaramaki commented
@ear-dev Can you please solve the conflicts?

2018-04-02 14:59 UTC, ear-dev commented
done.. thanks @leonardoaramaki

2018-04-25 02:26 UTC, rafaelks commented
@ear-dev Thanks for the PR! Just waiting for the conflicts to be solved in order to merge it.

2018-07-26 18:53 UTC, rafaelks commented
This bug is going to be handled by @luciofm in another PR. Thanks for the PR @ear-dev! 👍

2018-07-30 18:27 UTC, rafaelks commented
This one was fixed by #1548. Thanks @ear-dev!

2018-07-30 18:27 UTC, closed without merging