Navigate to profile on click on avatar
RocketChat/Rocket.Chat.Android pull request #992
Opened 2018-03-31 17:31 UTC by divyanshub024

@RocketChat/android

Closes #990 

This PR will allow a user to navigate to profile on click on avatar from navigation drawer.

![ezgif-5-4c8aced231](https://user-images.githubusercontent.com/16731434/38165807-1ec07582-3537-11e8-9608-9ad71beb2eec.gif)

2018-03-31 18:17 UTC, leonardoaramaki requested changes

2018-03-31 18:17 UTC, leonardoaramaki commented on app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
> +            view_navigation.menu.getItem(1).isChecked = true
Please user `view_navigation.menu.findItem(R.id.action_profile)` instead of getting by the index since it may change anytime.

2018-03-31 18:34 UTC, divyanshub024 commented
@leonardoaramaki requested changes are done.

2018-04-01 02:34 UTC, Shailesh351 approved these changes
LGTM

2018-04-01 15:21 UTC, leonardoaramaki approved these changes

2018-04-01 15:21 UTC, merged